version: '2'
networks:
  default:
    external:
      name: ggggg1
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_PORT=3307
     - PMA_HOST=192.168.1.9
    restart: always
    ports:
      - 80:80
  phpmyadmin2:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    environment:
     - PMA_PORT=3307
     - PMA_HOST=192.168.1.9
    restart: always
    ports:
      - 82:80